
server:
  port: 8088

spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
#    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://128.199.185.211:3307/db_orchid?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=True}
#    username: ${SPRING_DATASOURCE_USERNAME:root}
#    password: ${SPRING_DATASOURCE_PASSWORD:Abc123456789@}
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1057856726587-gbad25fkcea5rbr3u18p02l769tcota3.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

    #  datasource:
#    url: jdbc:mysql://localhost:3306/db_orchid
#    username: root
#    password: 12345

    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: true
    #properties.hibernate.dialect = org.hibernate.dialect.MySQL5InnoDBDialect
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  messages:
    basename: i18n/messages
    encoding: UTF-8
    default-locale: en
api:
  prefix: /api/v1

# swagger-ui custom path
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
  show-actuator: true

data:
  format: "yyyy-MM-dd'T'HH:mm:ss.SSS"
jwt:
#  expiration: 2592000 #30 days = 30 * 24 * 60 * 60
  expiration: 1800 #30 days = 30 * 24 * 60 * 60
  expiration-refresh-token: 5184000 #60 days = 60 * 24 * 60 * 60
  secretKey: TaqlmGv1iEDMRiFp/pHuID1+T84IABfuA0xXh4GhiUI=
logging:
  level:
    org:
      springframework.security: DEBUG

#health check
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /api/v1/actuator
      exposure:
        #include: "health"
        include: "health, info"


#url return payment
HOST:
  URL: ${HOST_URL:https://orchid.fams.io.vn/api/v1}

